language: node_js

node_js:
  - "node"

cache:
  npm: false

# Do not build feature branches
branches:
  only:
    - master
    - /^?([0-9]+\.){1,2}(x|[0-9]+)-?[a-z]*[1-9]*$/

before_script:
  - npm i -g jshint

# Test scripts
script:
  - npm test

jobs:
  include:
    - stage: npm release
      if: tag IS present
      node_js: "node"
      before_script:
        - npm install
      script:
        - npm build
      deploy:
        provider: npm
        email: "$NPM_MAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true
