language: node_js

node_js:
  - "node"

cache:
  npm: false

# Do not build feature branches
branches:
  only:
    - master
    - /^v?([0-9]+\.){1,2}(x|[0-9]+)-?[a-z]*[1-9]*$/

jobs:
  include:
    - stage: test
      node_js: "node"
      before_script:
        - npm i -g jshint
      script:
        - npm run test

    - stage: npm release
      if: tag IS present
      node_js: "node"
      before_script: skip
      script: skip
      deploy:
        provider: npm
        email: "$NPM_MAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true
